/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Design as PrismaDesign,
  Product as PrismaProduct,
} from "@prisma/client";
import { LocalStorageService } from "src/storage/providers/local/local.storage.service";
import { InputJsonValue } from "src/types";
import { FileDownload, FileUpload } from "src/storage/base/storage.types";
import { LocalStorageFile } from "src/storage/providers/local/local.storage.types";

export class DesignServiceBase {
  constructor(
    protected readonly prisma: PrismaService,
    protected readonly localStorageService: LocalStorageService
  ) {}

  async count(args: Omit<Prisma.DesignCountArgs, "select">): Promise<number> {
    return this.prisma.design.count(args);
  }

  async designs(args: Prisma.DesignFindManyArgs): Promise<PrismaDesign[]> {
    return this.prisma.design.findMany(args);
  }
  async design(
    args: Prisma.DesignFindUniqueArgs
  ): Promise<PrismaDesign | null> {
    return this.prisma.design.findUnique(args);
  }
  async createDesign(args: Prisma.DesignCreateArgs): Promise<PrismaDesign> {
    return this.prisma.design.create(args);
  }
  async updateDesign(args: Prisma.DesignUpdateArgs): Promise<PrismaDesign> {
    return this.prisma.design.update(args);
  }
  async deleteDesign(args: Prisma.DesignDeleteArgs): Promise<PrismaDesign> {
    return this.prisma.design.delete(args);
  }

  async uploadImageUrl<T extends Prisma.DesignFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DesignFindUniqueArgs>,
    file: FileUpload
  ): Promise<PrismaDesign> {
    file.filename = `profilePicture-${args.where.id}.${file.filename
      .split(".")
      .pop()}`;
    const containerPath = "imageUrl";
    const imageUrl = await this.localStorageService.uploadFile(
      file,
      [],
      1000000,
      containerPath
    );

    return await this.prisma.design.update({
      where: args.where,

      data: {
        imageUrl: imageUrl as InputJsonValue,
      },
    });
  }

  async downloadImageUrl<T extends Prisma.DesignFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DesignFindUniqueArgs>
  ): Promise<FileDownload> {
    const { imageUrl } = await this.prisma.design.findUniqueOrThrow({
      where: args.where,
    });

    return await this.localStorageService.downloadFile(
      imageUrl as unknown as LocalStorageFile
    );
  }

  async deleteImageUrl<T extends Prisma.DesignFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.DesignFindUniqueArgs>
  ): Promise<PrismaDesign> {
    const { imageUrl } = await this.prisma.design.findUniqueOrThrow({
      where: args.where,
    });

    await this.localStorageService.deleteFile(
      imageUrl as unknown as LocalStorageFile
    );

    return await this.prisma.design.update({
      where: args.where,

      data: {
        imageUrl: Prisma.DbNull,
      },
    });
  }

  async findProducts(
    parentId: string,
    args: Prisma.ProductFindManyArgs
  ): Promise<PrismaProduct[]> {
    return this.prisma.design
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .products(args);
  }
}
